name: flutter_shop
description: flutter shop app.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  #网络请求
  dio: ^4.0.6

  #下拉刷新
  pull_to_refresh_flutter3: ^2.0.1

  #对 InheritedWidget 组件的上层封装，使其更易用，更易复用。: https://github.com/rrousselGit/provider/blob/master/resources/translations/zh-CN/README.md
  provider: ^6.0.5

  #屏幕工具类
  flutter_screenutil: ^5.6.1

  #banner
  flutter_swiper_null_safety_flutter3: ^3.0.0

  #带缓存的Image
  cached_network_image: ^3.2.3

  #弹吐司
  fluttertoast: ^8.1.2

  #html插件
  flutter_widget_from_html_core: ^0.9.1

  #路由插件 ： https://pub.dev/packages/fluro
  fluro: ^2.0.4

  #sp工具类：https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.17

  #获取设备基础信息：https://pub.dev/packages/device_preview
#  device_preview: ^0.7.0

  # 可以作用滑动的组件，比如item的滑动删除等：https://pub.dev/packages/flutter_slidable
  flutter_slidable: ^2.0.0

  #城市列表选择器，中国的城市三级联动选择器： https://pub.dev/packages/city_pickers
  city_pickers: ^1.2.0

  #常用估计类
  flustars_flutter3: ^3.0.0

  #webview 插件
  webview_flutter: ^4.0.2

  #EventBus 插件
  event_bus: ^2.0.0

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
